apiVersion: skaffold/v1beta2
kind: Config
build:
        artifacts:
        - image: ryanvade/servicea
          context: servicea
        - image: ryanvade/serviceb
          context: serviceb
        - image: ryanvade/servicec
          context: servicec
deploy:
        kubectl:
                manifests:
                        - ./kubernetes-manifests/**.yaml
