apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: le-crt
  namespace: istio-system
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: skaffold-demo.uncomn.io
  dnsNames:
  - skaffold-demo.uncomn.io
